#!/usr/bin/env python

Import("env")
Import("env_modules")

env_warning_capture = env_modules.Clone()

env_warning_capture.add_source_files(env.modules_sources, "*.cpp")

# Check if building with editor support
if env.editor_build:
    env_warning_capture.add_source_files(env.modules_sources, "editor/*.cpp")