#!/usr/bin/env python

Import("env")
Import("env_modules")

env_warning_capture = env_modules.Clone()

# Note: Godot automatically defines MODULE_WARNING_CAPTURE_ENABLED when this module is enabled
# We use that define in upstream files to guard our additions

env_warning_capture.add_source_files(env.modules_sources, "*.cpp")

# Check if building with editor support
if env.editor_build:
    env_warning_capture.add_source_files(env.modules_sources, "editor/*.cpp")